### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by fjgordillo86** [blafois/Daikin-Madoka-BRC1H-BLE-Reverse#1]
![IMG_20210104_150649](https://user-images.githubusercontent.com/59791834/103548772-936f1380-4ea6-11eb-906b-d8227b5a8329.jpg)
Hi, I am experimenting with my madoka and the BLE Scanner app, I am sending the following commands over Bluetooth but they are not working quite right. See if you can help me, I'm sure I'm doing something wrong. 

- 0x000500402020 only turns madoka OFF and not ON. - 0x000500403020 turns madoka to fan mode. 
- 0x000500405021 puts the fan on auto. 

Could you tell me what would be the commands to send? So far I have only got the ones I have put.
Thanks.

**Comment by blafois** [comment]
Hello.
At a very first sight, I'm under impression that your messages are incomplete. For example, to turn on, I would go with:
`00 07 004020 20 01 01`
To turn off:
`00 07 004020 20 01 00`

When you provide arguments (after function ID), you need to provide, for each argument, the argument ID, following by the argument size (=length), plus the argument value. In the example you gave, you just provided argument id, but did not provide argument size+value.

Hope this helps

**Comment by fjgordillo86** [comment]
The failure was that the messages were incomplete, it was necessary to add what you comment. 
I'm going to continue playing with madoka, to see if I can control it from Home assistant. 
Thank you.
