### ISSUE TITLE
What is GFLOAT encoding

### ISSUE THREAD

**Issue by sglvladi** [blafois/Daikin-Madoka-BRC1H-BLE-Reverse#4]
Hi @blafois,

First of all, thanks for the awesome work on decoding the communication protocol.

I am currently in the process of configuring an ESP32 to connect and communicate with a Madoka device using Arduino.

One question (probably silly) that popped up while looking at "GetSetpoint()" and "SetSetpoint()" is: **what is "GFLOAT encoding"?** I tried Googling it, but got nothing.

Thanks much in advance.

**Comment by blafois** [comment]
Hi @sglvladi ,

Good question ! I must admit I don't remember where I did found the specification and name for this encoding, but I jumped on my notes - and here is how the encoding works:

Take your desired temperature, for example "20 degrees", and just multiply it by 128 - which is 2560 in dec or 0x0A00 in hex. This is how the temperatures are encoded for the Daikin thermostat.

Hope this helps ! 

Ben

**Comment by sglvladi** [comment]
@blafois Thank you! That's very helpful 👍
